language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip3 install -r requirements.txt
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
script: cd test && ./test.sh
